### ISSUE TITLE
This is amazing

### ISSUE THREAD

**Issue by shunkakinoki** [bishwenduk029/fringe#2]
Sorry for the non-issue, but I've been fascinated by the concept of `graphql-on-the-edge`.

I've seen ur graphql related PR on the @flareact project, only to come across this amazing repo!

Just wanted to say thank you and I am seriously in awe of your work!

**Comment by bishwenduk029** [comment]
@shunkakinoki , Thank you so much for your encouraging words means a lot. It is still in early stages and would love any feedback you have to share. Again thanks makes putting effort into it worthwhile.

**Comment by shunkakinoki** [comment]
Keep up the awesome work!
